### PR TITLE
Part 1

### PR DESCRIPTION
**Pull request by msano42**
**isalpha** and **isdgit**: Not sure why you casted character constants to int here (see image below), but please let me know if there's a technical reason why, I'm curious 👀 

IMG_0944

**isalnum**: You probably forgot to remove the <stdio.h> header you used for testing.

**isprint**: I know the man says "_returns non-zero if the character tests true_", but your blackhole is close so I thought probably not the best time to mess with the moulinette 💀  (I don't think you'd fail for returning 42 though.)

### CODE REVIEW

**Comment by msano42** [comment]
**strlen**: res **MUST** be size_t, for obvious reasons.

**memset**: Although your code won't have any problem with sign extension because you casted 'c' to unsigned char, I'd recommend also casting the destination pointer to **unsigned** char to maintain consistency across the code (and to be extra safe).

NB: Best practice would be to use unsigned char in most functions where you deal with memory directly, so that you're accessing all 8 bits of the raw bytes (assuming two's complement encoding and 8 bit bytes of course 😉).

**memcpy** and **memmove**: I'm aware the behaviour of these functions is undefined with NULL pointers, but to be extra safe you could protect your functions just for submission. It most likely will pass the moulinette though, so I didn't change anything here.

**Comment by msano42** [comment]
**strncmp**: putting "i <= n" first protects the function from segfault in cases where s1 or s2 is NULL but n = 0.

**strnstr**: Your code segfaults when n is greater than the length of haystack (see man extract below).

 _The strnstr() function locates the first occurrence of the null-terminated string s2 in the string s1, where not more than n characters are searched. **Characters that appear after a `\0' character are not searched**._

I modified the algorithm a bit because I got KO's with the following tester (I've included the test cases in the main function):

https://github.com/Tripouille/libftTester.git

**Comment by msano42** [comment]
**strdup**: I thought the +1 was unnecessary but strlcpy will protect the operation anyways as it stops at the null character of src anyways.

**calloc**: added some protection for when count * size is greater than SIZE_MAX (see article below).

https://wiki.sei.cmu.edu/confluence/display/c/MEM07-C.+Ensure+that+the+arguments+to+calloc%28%29%2C+when+multiplied%2C+do+not+wrap

**Comment by b10s** [comment]
Thank you for such thorough review!

I fixed bugs mentioned by you.

**Pull request merged**
